# Used by: https://github.com/tom-pollak/lazygit-vscode
os:
  edit:              "agy --reuse-window -- {{filename}}"
  editAtLine:        "agy --reuse-window --goto -- {{filename}}:{{line}}"
  editAtLineAndWait: "agy --reuse-window --goto --wait -- {{filename}}:{{line}}"
  openDirInEditor:   "agy -- {{dir}}"
promptToReturnFromSubprocess: false
git:
  pagers:
    - pager: delta $(defaults read -g AppleInterfaceStyle >/dev/null 2>&1 && echo --dark || echo --light) --paging=never
