os:
  editPreset: 'zed'
promptToReturnFromSubprocess: false
git:
  diffRenderers:
    - command: delta $(defaults read -g AppleInterfaceStyle >/dev/null 2>&1 && echo --dark || echo --light) --paging=never
